### ISSUE TITLE
Segfault when loading libraries with python2

### ISSUE THREAD

**Issue by cclaessens** [project8/cicada#8]
```ῢ2018-04-10T17:16:22[DEBUG   ] CicadaPy(46) -> Import libraries...
2018-04-10T17:16:22[DEBUG   ] CicadaPy(51) -> 	->/home/chrischtel/repos/cicada/build/lib/libCicada.so
TClassTable::Add:0: RuntimeWarning: class TROOT already in TClassTable
TClassTable::Add:0: RuntimeWarning: class timespec already in TClassTable

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 2 (Thread 0x7f5649371700 (LWP 14082)):
#0  0x00007f564fe97827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x1252200) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem
entry=0x1252200, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f564fe978d4 in __new_sem_wait_slow (sem=0x1252200, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f564fe9797a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000494f34 in PyThread_acquire_lock ()
#5  0x00000000004a40e1 in PyImport_ImportModuleLevel ()
#6  0x00000000004a59e4 in ?? ()
#7  0x00000000004c30ce in PyEval_EvalFrameEx ()
#8  0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#9  0x00000000004d54b9 in ?? ()
#10 0x00000000004a577e in PyObject_Call ()
#11 0x00000000004c5e10 in PyEval_CallObjectWithKeywords ()
#12 0x00000000004be6d7 in PyEval_EvalFrameEx ()
#13 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#14 0x00000000004d55f3 in ?? ()
#15 0x00000000004a577e in PyObject_Call ()
#16 0x00000000004bed3d in PyEval_EvalFrameEx ()
#17 0x00000000004c136f in PyEval_EvalFrameEx ()
#18 0x00000000004c136f in PyEval_EvalFrameEx ()
#19 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#20 0x00000000004d54b9 in ?? ()
#21 0x00000000004eebee in ?? ()
#22 0x00000000004a577e in PyObject_Call ()
#23 0x00000000004c5e10 in PyEval_CallObjectWithKeywords ()
#24 0x0000000000589172 in ?? ()
#25 0x00007f564fe8f6ba in start_thread (arg=0x7f5649371700) at pthread_create.c:333
#26 0x00007f564fbc541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f5650296700 (LWP 14070)):
#0  0x00007f564fb8a0cb in __GI___waitpid (pid=14085, stat_loc=stat_loc
entry=0x7ffd50971480, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f564fb02fbb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f564da8fdd4 in TUnixSystem::StackTrace() () from /usr/lib/x86_64-linux-gnu/libCore.so.5.34
#3  0x00007f564da9203c in TUnixSystem::DispatchSignals(ESignals) () from /usr/lib/x86_64-linux-gnu/libCore.so.5.34
#4  <signal handler called>
#5  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:70
#6  0x00007f5648556c1c in std::char_traits<char>::compare (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>) at /usr/include/c++/5/bits/char_traits.h:262
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (__str="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x7f564d9bd9e0 <TString::ReadBuffer(char*&)+32>) at /usr/include/c++/5/bits/basic_string.h:2318
#8  std::operator< <char, std::char_traits<char>, std::allocator<char> > (__rhs="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __lhs=<error: Cannot access memory at address 0x845c703>) at /usr/include/c++/5/bits/basic_string.h:4989
#9  std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (this=<optimized out>, __y="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __x=<error: Cannot access memory at address 0x845c703>) at /usr/include/c++/5/bits/stl_function.h:387
#10 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::_M_lower_bound (this=<optimized out>, __k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __y=0x12fd088, __x=0x7f564d9bd9c0 <TString::ReadBuffer(char*&)>) at /usr/include/c++/5/bits/stl_tree.h:1628
#11 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::lower_bound (__k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_tree.h:1091
#12 std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::TClassRec*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::lower_bound (__x="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_map.h:916
#13 std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::TClassRec*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::operator[] (__k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_map.h:479
#14 ROOT::TMapTypeToClassRec::Add (obj=<synthetic pointer>, key="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /home/chrischtel/repos/root6/root-6.08.06/core/cont/src/TClassTable.cxx:122
#15 TClassTable::Add (cname=<optimized out>, id=<optimized out>, info=..., dict=<optimized out>, pragmabits=<optimized out>) at /home/chrischtel/repos/root6/root-6.08.06/core/cont/src/TClassTable.cxx:351
#16 0x00007f56485c2083 in ROOT::TGenericClassInfo::TGenericClassInfo (this=0x7f56488fac40 <ROOT::GenerateInitInstanceLocal(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const*)::instance>, fullClassname=<optimized out>, declFileName=<optimized out>, declFileLine=<optimized out>, info=..., action=<optimized out>, dictionary=0x7f564847fc30 <ROOT::__gnu_cxxcLcL__normal_iteratorlEcharmUcOstringgR_Dictionary()>, isa=0x21701f0, pragmabits=0, sizof=8) at /home/chrischtel/repos/root6/root-6.08.06/core/meta/src/TGenericClassInfo.cxx:59
#17 0x00007f564847fb6e in ROOT::GenerateInitInstanceLocal () at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:368
#18 0x00007f5648458634 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:383
#19 _GLOBAL__sub_I_G__Core.cxx(void) () at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:27629
#20 0x00007f56500b56ba in call_init (l=<optimized out>, argc=argc
entry=2, argv=argv
entry=0x7ffd50975a88, env=env
entry=0x1324ef0) at dl-init.c:72
#21 0x00007f56500b57cb in call_init (env=0x1324ef0, argv=0x7ffd50975a88, argc=2, l=<optimized out>) at dl-init.c:30
#22 _dl_init (main_map=main_map
entry=0x125b250, argc=2, argv=0x7ffd50975a88, env=0x1324ef0) at dl-init.c:120
#23 0x00007f56500ba8e2 in dl_open_worker (a=a
entry=0x7ffd50974160) at dl-open.c:575
#24 0x00007f56500b5564 in _dl_catch_error (objname=objname
entry=0x7ffd50974150, errstring=errstring
entry=0x7ffd50974158, mallocedp=mallocedp
entry=0x7ffd5097414f, operate=operate
entry=0x7f56500ba4d0 <dl_open_worker>, args=args
entry=0x7ffd50974160) at dl-error.c:187
#25 0x00007f56500b9da9 in _dl_open (file=0x7f564d36b8ae <G(int, float, int, long,...)+14> "/home/chrischtel/repos/cicada/build/lib/libCicada.so", mode=-2147483391, caller_dlopen=0x7f564cf505a6 <G__dlopen+86>, nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x1324ef0) at dl-open.c:660
#26 0x00007f564f8baf09 in dlopen_doit (a=a
entry=0x7ffd50974390) at dlopen.c:66
#27 0x00007f56500b5564 in _dl_catch_error (objname=0x12e6ec0, errstring=0x12e6ec8, mallocedp=0x12e6eb8, operate=0x7f564f8baeb0 <dlopen_doit>, args=0x7ffd50974390) at dl-error.c:187
#28 0x00007f564f8bb571 in _dlerror_run (operate=operate
entry=0x7f564f8baeb0 <dlopen_doit>, args=args
entry=0x7ffd50974390) at dlerror.c:163
#29 0x00007f564f8bafa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#30 0x00007f564cf505a6 in G__dlopen () from /usr/lib/x86_64-linux-gnu/libCint.so.5.34
#31 0x00007f564cf53bf7 in G__shl_load () from /usr/lib/x86_64-linux-gnu/libCint.so.5.34
#32 0x00007f564cf42d88 in G__loadfile () from /usr/lib/x86_64-linux-gnu/libCint.so.5.34
#33 0x00007f564da50fb0 in TCint::Load(char const*, bool) () from /usr/lib/x86_64-linux-gnu/libCore.so.5.34
#34 0x00007f564da0744c in TSystem::Load(char const*, char const*, bool) () from /usr/lib/x86_64-linux-gnu/libCore.so.5.34
#35 0x00007f564db93715 in ?? () from /usr/lib/x86_64-linux-gnu/libCore.so.5.34
#36 0x00007f564d0247bb in Cint::G__CallFunc::Execute(void*) () from /usr/lib/x86_64-linux-gnu/libCint.so.5.34
#37 0x00007f564e1bad4a in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /usr/lib/x86_64-linux-gnu/root5.34/libPyROOT.so
#38 0x00007f564e1b7216 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /usr/lib/x86_64-linux-gnu/root5.34/libPyROOT.so
#39 0x00007f564e1b7380 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /usr/lib/x86_64-linux-gnu/root5.34/libPyROOT.so
#40 0x00007f564e1b6dc1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /usr/lib/x86_64-linux-gnu/root5.34/libPyROOT.so
#41 0x00007f564e1a165f in ?? () from /usr/lib/x86_64-linux-gnu/root5.34/libPyROOT.so
#42 0x00000000004c15bf in PyEval_EvalFrameEx ()
#43 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#44 0x00000000004c16e7 in PyEval_EvalFrameEx ()
#45 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#46 0x00000000004b97a6 in PyEval_EvalCode ()
#47 0x00000000004b96df in PyImport_ExecCodeModuleEx ()
#48 0x00000000004b2b06 in ?? ()
#49 0x00000000004a4ae1 in ?? ()
#50 0x00000000004a3e84 in PyImport_ImportModuleLevel ()
#51 0x00000000004a59e4 in ?? ()
#52 0x00000000004a577e in PyObject_Call ()
#53 0x00000000004c5e10 in PyEval_CallObjectWithKeywords ()
#54 0x00000000004be6d7 in PyEval_EvalFrameEx ()
#55 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#56 0x00000000004eb30f in ?? ()
#57 0x00000000004e5422 in PyRun_FileExFlags ()
#58 0x00000000004e3cd6 in PyRun_SimpleFileExFlags ()
#59 0x0000000000493ae2 in Py_Main ()
#60 0x00007f564fade830 in __libc_start_main (main=0x4934c0 <main>, argc=2, argv=0x7ffd50975a88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd50975a78) at ../csu/libc-start.c:291
#61 0x00000000004933e9 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:70
#6  0x00007f5648556c1c in std::char_traits<char>::compare (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>) at /usr/include/c++/5/bits/char_traits.h:262
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (__str="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x7f564d9bd9e0 <TString::ReadBuffer(char*&)+32>) at /usr/include/c++/5/bits/basic_string.h:2318
#8  std::operator< <char, std::char_traits<char>, std::allocator<char> > (__rhs="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __lhs=<error: Cannot access memory at address 0x845c703>) at /usr/include/c++/5/bits/basic_string.h:4989
#9  std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator() (this=<optimized out>, __y="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __x=<error: Cannot access memory at address 0x845c703>) at /usr/include/c++/5/bits/stl_function.h:387
#10 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::_M_lower_bound (this=<optimized out>, __k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", __y=0x12fd088, __x=0x7f564d9bd9c0 <TString::ReadBuffer(char*&)>) at /usr/include/c++/5/bits/stl_tree.h:1628
#11 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::lower_bound (__k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_tree.h:1091
#12 std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::TClassRec*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::lower_bound (__x="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_map.h:916
#13 std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::TClassRec*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ROOT::TClassRec*> > >::operator[] (__k="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /usr/include/c++/5/bits/stl_map.h:479
#14 ROOT::TMapTypeToClassRec::Add (obj=<synthetic pointer>, key="N9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE", this=0x12fd080) at /home/chrischtel/repos/root6/root-6.08.06/core/cont/src/TClassTable.cxx:122
#15 TClassTable::Add (cname=<optimized out>, id=<optimized out>, info=..., dict=<optimized out>, pragmabits=<optimized out>) at /home/chrischtel/repos/root6/root-6.08.06/core/cont/src/TClassTable.cxx:351
#16 0x00007f56485c2083 in ROOT::TGenericClassInfo::TGenericClassInfo (this=0x7f56488fac40 <ROOT::GenerateInitInstanceLocal(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const*)::instance>, fullClassname=<optimized out>, declFileName=<optimized out>, declFileLine=<optimized out>, info=..., action=<optimized out>, dictionary=0x7f564847fc30 <ROOT::__gnu_cxxcLcL__normal_iteratorlEcharmUcOstringgR_Dictionary()>, isa=0x21701f0, pragmabits=0, sizof=8) at /home/chrischtel/repos/root6/root-6.08.06/core/meta/src/TGenericClassInfo.cxx:59
#17 0x00007f564847fb6e in ROOT::GenerateInitInstanceLocal () at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:368
#18 0x00007f5648458634 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:383
#19 _GLOBAL__sub_I_G__Core.cxx(void) () at /home/chrischtel/repos/root6/build/core/base/G__Core.cxx:27629
#20 0x00007f56500b56ba in call_init (l=<optimized out>, argc=argc
entry=2, argv=argv
entry=0x7ffd50975a88, env=env
entry=0x1324ef0) at dl-init.c:72
#21 0x00007f56500b57cb in call_init (env=0x1324ef0, argv=0x7ffd50975a88, argc=2, l=<optimized out>) at dl-init.c:30
#22 _dl_init (main_map=main_map
entry=0x125b250, argc=2, argv=0x7ffd50975a88, env=0x1324ef0) at dl-init.c:120
#23 0x00007f56500ba8e2 in dl_open_worker (a=a
entry=0x7ffd50974160) at dl-open.c:575
#24 0x00007f56500b5564 in _dl_catch_error (objname=objname
entry=0x7ffd50974150, errstring=errstring
entry=0x7ffd50974158, mallocedp=mallocedp
entry=0x7ffd5097414f, operate=operate
entry=0x7f56500ba4d0 <dl_open_worker>, args=args
entry=0x7ffd50974160) at dl-error.c:187
#25 0x00007f56500b9da9 in _dl_open (file=0x7f564d36b8ae <G(int, float, int, long,...)+14> "/home/chrischtel/repos/cicada/build/lib/libCicada.so", mode=-2147483391, caller_dlopen=0x7f564cf505a6 <G__dlopen+86>, nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x1324ef0) at dl-open.c:660
#26 0x00007f564f8baf09 in dlopen_doit (a=a
entry=0x7ffd50974390) at dlopen.c:66
#27 0x00007f56500b5564 in _dl_catch_error (objname=0x12e6ec0, errstring=0x12e6ec8, mallocedp=0x12e6eb8, operate=0x7f564f8baeb0 <dlopen_doit>, args=0x7ffd50974390) at dl-error.c:187
#28 0x00007f564f8bb571 in _dlerror_run (operate=operate
entry=0x7f564f8baeb0 <dlopen_doit>, args=args
entry=0x7ffd50974390) at dlerror.c:163
#29 0x00007f564f8bafa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
===========================================================


Traceback (most recent call last):
  File "trigger_analysis.py", line 13, in <module>
    from ReadKTOutputFile import *
  File "/home/chrischtel/repos/cicada/build/ReadKTOutputFile.py", line 8, in <module>
    CicadaPy.loadLibraries()
  File "/home/chrischtel/repos/cicada/build/CicadaPy.py", line 52, in loadLibraries
    gSystem.Load(os.path.join(path, afile))
SystemError: problem in C++; program state has been reset
Segmentation fault
```

**Comment by guiguem** [comment]
I couldnot reproduce this error using a python2-ROOT docker to build and test cicada
